#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Inline
Version  : 0.80
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/I/IN/INGY/Inline-0.80.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/I/IN/INGY/Inline-0.80.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libi/libinline-perl/libinline-perl_0.80-1.debian.tar.xz
Summary  : 'Write Perl Subroutines in Other Programming Languages'
Group    : Development/Tools
License  : Artistic-1.0-Perl
Requires: perl-Inline-man
BuildRequires : perl(Sub::Uplevel)
BuildRequires : perl(Test::Warn)

%description
NAME
Inline - Write Perl Subroutines in Other Programming Languages
VERSION
This document describes Inline version 0.80.

%package man
Summary: man components for the perl-Inline package.
Group: Default

%description man
man components for the perl-Inline package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n Inline-0.80
mkdir -p %{_topdir}/BUILD/Inline-0.80/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/Inline-0.80/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/Inline.pm
/usr/lib/perl5/site_perl/5.26.1/Inline.pod
/usr/lib/perl5/site_perl/5.26.1/Inline/API.pod
/usr/lib/perl5/site_perl/5.26.1/Inline/FAQ.pod
/usr/lib/perl5/site_perl/5.26.1/Inline/Foo.pm
/usr/lib/perl5/site_perl/5.26.1/Inline/MakeMaker.pm
/usr/lib/perl5/site_perl/5.26.1/Inline/MakeMaker/Changes
/usr/lib/perl5/site_perl/5.26.1/Inline/Support.pod
/usr/lib/perl5/site_perl/5.26.1/Inline/denter.pm

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/Inline.3
/usr/share/man/man3/Inline::API.3
/usr/share/man/man3/Inline::FAQ.3
/usr/share/man/man3/Inline::Support.3
